FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install streamlit requests --no-cache-dir 

CMD ["streamlit", "run", "streamlit.py", "--server.port=8501", "--server.address=0.0.0.0","--server.baseUrlPath=/chat/"]
